# Summary

In this notebook, the Bank Marketing dataset was successfully prepared for machine learning.

The preprocessing pipeline included:

- Loading the dataset
- Exploring the dataset structure
- Handling duplicate records
- Identifying feature types
- Encoding categorical variables
- Encoding the target variable
- Scaling numerical features
- Splitting the dataset into training and testing sets
- Saving the processed datasets
- Saving preprocessing objects for future use

The processed data is now ready for training baseline machine learning models in the next notebook.

In [1]:
# ============================
# Import Required Libraries
# ============================

import os
import joblib
import warnings

import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

warnings.filterwarnings("ignore")

# Load Processed Dataset

The processed dataset created in Notebook 1 is loaded for model training and evaluation.

In [2]:
# ============================
# Load Processed Data
# ============================

X_train = pd.read_csv("../data/processed/X_train.csv")
X_test = pd.read_csv("../data/processed/X_test.csv")

y_train = pd.read_csv("../data/processed/y_train.csv")["target"]
y_test = pd.read_csv("../data/processed/y_test.csv")["target"]

print("Training Shape :", X_train.shape)
print("Testing Shape  :", X_test.shape)

Training Shape : (32940, 20)
Testing Shape  : (8236, 20)

# Create Results Storage

A list is created to store the evaluation metrics of all baseline models.

In [3]:
# ============================
# Results Storage
# ============================

results = []

# Logistic Regression

Logistic Regression is one of the most commonly used baseline classification algorithms. It is simple, interpretable, and computationally efficient.

In [4]:
# ============================
# Logistic Regression
# ============================

logreg = LogisticRegression(random_state=42)

logreg.fit(X_train, y_train)

logreg_pred = logreg.predict(X_test)

In [5]:
# Logistic Regression Metrics

logreg_accuracy = accuracy_score(y_test, logreg_pred)
logreg_precision = precision_score(y_test, logreg_pred)
logreg_recall = recall_score(y_test, logreg_pred)
logreg_f1 = f1_score(y_test, logreg_pred)

print(classification_report(y_test, logreg_pred))

              precision    recall  f1-score   support

           0       0.93      0.97      0.95      7308
           1       0.66      0.42      0.51       928

    accuracy                           0.91      8236
   macro avg       0.79      0.70      0.73      8236
weighted avg       0.90      0.91      0.90      8236

In [6]:
results.append({
    "Model": "Logistic Regression",
    "Accuracy": logreg_accuracy,
    "Precision": logreg_precision,
    "Recall": logreg_recall,
    "F1 Score": logreg_f1
})

# Decision Tree Classifier

Decision Trees learn decision rules from the training data and are widely used as baseline models because they are easy to understand and visualize.

In [7]:
# ============================
# Decision Tree
# ============================

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

In [8]:
dt_accuracy = accuracy_score(y_test, dt_pred)
dt_precision = precision_score(y_test, dt_pred)
dt_recall = recall_score(y_test, dt_pred)
dt_f1 = f1_score(y_test, dt_pred)

print(classification_report(y_test, dt_pred))

              precision    recall  f1-score   support

           0       0.94      0.93      0.94      7308
           1       0.51      0.55      0.53       928

    accuracy                           0.89      8236
   macro avg       0.73      0.74      0.73      8236
weighted avg       0.89      0.89      0.89      8236

In [9]:
results.append({
    "Model": "Decision Tree",
    "Accuracy": dt_accuracy,
    "Precision": dt_precision,
    "Recall": dt_recall,
    "F1 Score": dt_f1
})

# Random Forest Classifier

Random Forest combines multiple decision trees to improve prediction accuracy and reduce overfitting. It serves as a stronger baseline model.

In [10]:
# ============================
# Random Forest
# ============================

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

In [11]:
rf_accuracy = accuracy_score(y_test, rf_pred)
rf_precision = precision_score(y_test, rf_pred)
rf_recall = recall_score(y_test, rf_pred)
rf_f1 = f1_score(y_test, rf_pred)

print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           0       0.94      0.96      0.95      7308
           1       0.65      0.54      0.59       928

    accuracy                           0.92      8236
   macro avg       0.80      0.75      0.77      8236
weighted avg       0.91      0.92      0.91      8236

In [12]:
results.append({
    "Model": "Random Forest",
    "Accuracy": rf_accuracy,
    "Precision": rf_precision,
    "Recall": rf_recall,
    "F1 Score": rf_f1
})

# Model Comparison

The evaluation metrics of all baseline models are combined into a single comparison table.

In [13]:
baseline_results = pd.DataFrame(results)

baseline_results

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.910272   0.660441  0.419181  0.512854
1        Decision Tree  0.890238   0.512121  0.546336  0.528676
2        Random Forest  0.915493   0.651436  0.537716  0.589138

In [14]:
baseline_results.sort_values(
    by="Accuracy",
    ascending=False
)

                 Model  Accuracy  Precision    Recall  F1 Score
2        Random Forest  0.915493   0.651436  0.537716  0.589138
0  Logistic Regression  0.910272   0.660441  0.419181  0.512854
1        Decision Tree  0.890238   0.512121  0.546336  0.528676

# Save Baseline Models

The trained models are saved for future prediction and comparison with advanced models.

In [15]:
joblib.dump(logreg, "../models/baseline_logreg.pkl")

joblib.dump(dt, "../models/baseline_dt.pkl")

joblib.dump(rf, "../models/baseline_rf.pkl")

print("Baseline models saved successfully.")

Baseline models saved successfully.

# Save Evaluation Results

The evaluation metrics are exported as a CSV file for use in the final model comparison notebook.

In [16]:
os.makedirs("../outputs/model_results", exist_ok=True)

baseline_results.to_csv(
    "../outputs/model_results/baseline_metrics.csv",
    index=False
)

print("Baseline metrics saved successfully.")

Baseline metrics saved successfully.

# Conclusion

In this notebook, three baseline machine learning models were trained and evaluated:

- Logistic Regression
- Decision Tree Classifier
- Random Forest Classifier

Their performance metrics were exported for comparison with advanced machine learning models in the next notebook.