# Day 20 - Advanced Machine Learning Models

## Cooperative Tech Private Limited - AI/ML Internship

### Objective

This notebook focuses on training advanced machine learning models using the preprocessed Bank Marketing dataset.

The following tasks will be performed:

- Load processed data
- Train Gradient Boosting
- Train XGBoost
- Train Support Vector Machine (SVM)
- Evaluate each model
- Compare model performance
- Save trained models
- Export evaluation metrics

These models will later be compared with the baseline models to identify the best-performing algorithm.

In [2]:
# ============================
# Import Required Libraries
# ============================

import os
import joblib
import warnings

import pandas as pd

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

import xgboost as xgb

warnings.filterwarnings("ignore")

# Load Processed Dataset

The processed training and testing datasets created in Notebook 1 are loaded for advanced model training.

In [3]:
# ============================
# Load Dataset
# ============================

X_train = pd.read_csv("../data/processed/X_train.csv")
X_test = pd.read_csv("../data/processed/X_test.csv")

y_train = pd.read_csv("../data/processed/y_train.csv")["target"]
y_test = pd.read_csv("../data/processed/y_test.csv")["target"]

print(X_train.shape)
print(X_test.shape)

(32940, 20)
(8236, 20)

# Create Results Storage

A list is created to store the evaluation metrics of all advanced models.

In [4]:
results = []

# Gradient Boosting Classifier

Gradient Boosting builds trees sequentially, where each tree attempts to correct the mistakes of the previous one.

In [5]:
gb = GradientBoostingClassifier(random_state=42)

gb.fit(X_train, y_train)

gb_pred = gb.predict(X_test)

In [6]:
gb_accuracy = accuracy_score(y_test, gb_pred)
gb_precision = precision_score(y_test, gb_pred)
gb_recall = recall_score(y_test, gb_pred)
gb_f1 = f1_score(y_test, gb_pred)

print(classification_report(y_test, gb_pred))

              precision    recall  f1-score   support

           0       0.95      0.96      0.95      7308
           1       0.66      0.56      0.61       928

    accuracy                           0.92      8236
   macro avg       0.80      0.76      0.78      8236
weighted avg       0.91      0.92      0.92      8236

In [7]:
results.append({
    "Model":"Gradient Boosting",
    "Accuracy":gb_accuracy,
    "Precision":gb_precision,
    "Recall":gb_recall,
    "F1 Score":gb_f1
})

# XGBoost Classifier

XGBoost is an optimized implementation of Gradient Boosting that is widely used in industry because of its speed and predictive performance.

In [8]:
xgb_model = xgb.XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

xgb_model.fit(X_train, y_train)

xgb_pred = xgb_model.predict(X_test)

In [9]:
xgb_accuracy = accuracy_score(y_test, xgb_pred)
xgb_precision = precision_score(y_test, xgb_pred)
xgb_recall = recall_score(y_test, xgb_pred)
xgb_f1 = f1_score(y_test, xgb_pred)

print(classification_report(y_test, xgb_pred))

              precision    recall  f1-score   support

           0       0.95      0.96      0.95      7308
           1       0.63      0.56      0.59       928

    accuracy                           0.91      8236
   macro avg       0.79      0.76      0.77      8236
weighted avg       0.91      0.91      0.91      8236

In [10]:
results.append({
    "Model":"XGBoost",
    "Accuracy":xgb_accuracy,
    "Precision":xgb_precision,
    "Recall":xgb_recall,
    "F1 Score":xgb_f1
})

# Support Vector Machine (SVM)

Support Vector Machine is a supervised learning algorithm that identifies the optimal decision boundary for separating different classes.

In [11]:
svm = SVC(random_state=42)

svm.fit(X_train, y_train)

svm_pred = svm.predict(X_test)

In [12]:
svm_accuracy = accuracy_score(y_test, svm_pred)
svm_precision = precision_score(y_test, svm_pred)
svm_recall = recall_score(y_test, svm_pred)
svm_f1 = f1_score(y_test, svm_pred)

print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95      7308
           1       0.68      0.34      0.45       928

    accuracy                           0.91      8236
   macro avg       0.80      0.66      0.70      8236
weighted avg       0.89      0.91      0.89      8236

In [13]:
results.append({
    "Model":"Support Vector Machine",
    "Accuracy":svm_accuracy,
    "Precision":svm_precision,
    "Recall":svm_recall,
    "F1 Score":svm_f1
})

# Advanced Model Comparison

The performance of all advanced machine learning models is summarized in a comparison table.

In [14]:
advanced_results = pd.DataFrame(results)

advanced_results

                    Model  Accuracy  Precision    Recall  F1 Score
0       Gradient Boosting  0.918286   0.660782  0.564655  0.608948
1                 XGBoost  0.913065   0.626794  0.564655  0.594104
2  Support Vector Machine  0.907479   0.681223  0.336207  0.450216

In [15]:
advanced_results.sort_values(
    by="Accuracy",
    ascending=False
)

                    Model  Accuracy  Precision    Recall  F1 Score
0       Gradient Boosting  0.918286   0.660782  0.564655  0.608948
1                 XGBoost  0.913065   0.626794  0.564655  0.594104
2  Support Vector Machine  0.907479   0.681223  0.336207  0.450216

# Save Trained Models

The trained advanced models are saved for future use and deployment.

In [16]:
joblib.dump(gb,"../models/gradient_boosting.pkl")

joblib.dump(xgb_model,"../models/xgboost.pkl")

joblib.dump(svm,"../models/svm.pkl")

print("Advanced models saved successfully.")

Advanced models saved successfully.

# Save Evaluation Results

The evaluation metrics of all advanced models are exported as a CSV file for comparison in the next notebook.

In [17]:
os.makedirs("../outputs/model_results",exist_ok=True)

advanced_results.to_csv(
    "../outputs/model_results/advanced_metrics.csv",
    index=False
)

print("Advanced metrics saved successfully.")

Advanced metrics saved successfully.

# Conclusion

In this notebook, three advanced machine learning models were successfully trained and evaluated:

- Gradient Boosting
- XGBoost
- Support Vector Machine (SVM)

The trained models and evaluation metrics have been saved for use in the final model comparison notebook.